dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install -r requirements-test.txt
  - pyrobuf proto/osm.proto --out-dir osmgeodb

script:
  - python setup.py build_ext --inplace
  - mypy osmgeodb
  - pytest -vv
